package auto01.base;

import io.qameta.allure.Attachment;
import org.testng.ITestResult;
import org.testng.TestListenerAdapter;
import org.testng.Reporter;
import java.util.List;

public class AllureTestListener extends TestListenerAdapter {

    // Method to attach the logs as a string to the Allure report
    @Attachment(value = "Console Output", type = "text/plain")
    public static String attachConsoleOutput(List<String> outputList) {
        StringBuilder output = new StringBuilder();
        for (String o : outputList) {
//            output.append(o).append("<br/>"); // Using <br/> for line breaks in HTML report
            output.append(o);
        }
        return output.toString();
    }

    @Override
    public void onTestSuccess(ITestResult testResult) {
        // Get all logs generated by Reporter.log() during the test method execution
        List<String> output = Reporter.getOutput(testResult);
        if (!output.isEmpty()) {
            attachConsoleOutput(output);
        }
        super.onTestSuccess(testResult);
    }

    @Override
    public void onTestFailure(ITestResult testResult) {
        // Capture logs on test failure as well
        List<String> output = Reporter.getOutput(testResult);
        if (!output.isEmpty()) {
            attachConsoleOutput(output);
        }
        super.onTestFailure(testResult);
    }
    // You can override onTestSkipped, onConfigurationFailure, etc.
}

